Repository TelePigeon/TelePigeon-Server, pull requests merged in 2024-08, with the labels that each got.

#115 [fix] 월간 키워드 조회 수정
  src/main/java/com/telepigeon/server/service/answer/AnswerService.java
Labels: 🛠️ fix ⚒️

#119 [fix] 걱정 전송 기능 수정 및 비동기 적용
  src/main/java/com/telepigeon/server/config/AsyncConfig.java
  src/main/java/com/telepigeon/server/domain/Profile.java
  src/main/java/com/telepigeon/server/domain/Worry.java
  src/main/java/com/telepigeon/server/service/ScheduleService.java
Labels: 🛠️ fix ⚒️

#123 [chore] 시연 영상 및 공모전 위한 로깅 추가
  src/main/java/com/telepigeon/server/domain/Worry.java
  src/main/java/com/telepigeon/server/dto/fcm/FcmMessageDto.java
  src/main/java/com/telepigeon/server/service/answer/AnswerService.java
  src/main/java/com/telepigeon/server/service/external/FcmService.java
  src/main/java/com/telepigeon/server/service/hurry/HurryService.java
  src/main/java/com/telepigeon/server/service/question/QuestionService.java
  src/main/java/com/telepigeon/server/service/room/RoomService.java
Labels: ➰ chore ➰

#129 [feat] 시연용 테스트API 생성
  src/main/java/com/telepigeon/server/controller/TestController.java
  src/main/java/com/telepigeon/server/service/profile/ProfileRetriever.java
Labels: ✨ feat ✨
