Repository TelePigeon/TelePigeon-Server, pull requests merged in 2024-06, with the labels that each got.

#47 [feat] Security, JWT 적용
  build.gradle
  src/main/java/com/telepigeon/server/config/WebConfig.java
  src/main/java/com/telepigeon/server/constant/AuthConstant.java
  src/main/java/com/telepigeon/server/controller/AuthController.java
  src/main/java/com/telepigeon/server/controller/TestController.java
  src/main/java/com/telepigeon/server/domain/Token.java
  src/main/java/com/telepigeon/server/exception/ForbiddenException.java
  src/main/java/com/telepigeon/server/exception/UnAuthorizedException.java
  src/main/java/com/telepigeon/server/exception/code/ForbiddenErrorCode.java
  src/main/java/com/telepigeon/server/exception/code/UnAuthorizedErrorCode.java
  src/main/java/com/telepigeon/server/oauth/service/KakaoService.java
  src/main/java/com/telepigeon/server/repository/TokenRepository.java
  src/main/java/com/telepigeon/server/resolver/UserIdArgumentResolver.java
  src/main/java/com/telepigeon/server/security/config/SecurityConfig.java
  src/main/java/com/telepigeon/server/security/filter/FilterUtil.java
  src/main/java/com/telepigeon/server/security/filter/JwtAuthenticationFilter.java
  src/main/java/com/telepigeon/server/security/filter/JwtExceptionFilter.java
  src/main/java/com/telepigeon/server/security/handler/JwtAuthenticationEntryPoint.java
  src/main/java/com/telepigeon/server/security/info/UserAuthentication.java
  src/main/java/com/telepigeon/server/service/auth/AuthService.java
  src/main/java/com/telepigeon/server/service/auth/TokenRetriever.java
  src/main/java/com/telepigeon/server/service/question/QuestionService.java
  src/main/java/com/telepigeon/server/utils/JwtUtil.java
Labels: ➰ chore ➰, ✨ feat ✨

#50 [refac] FcmService 리팩토링
  src/main/java/com/telepigeon/server/config/FirebaseConfig.java
  src/main/java/com/telepigeon/server/dto/fcm/FcmMessageDto.java
  src/main/java/com/telepigeon/server/dto/type/FcmContent.java
  src/main/java/com/telepigeon/server/exception/code/NotFoundErrorCode.java
  src/main/java/com/telepigeon/server/service/answer/AnswerService.java
  src/main/java/com/telepigeon/server/service/fcm/FcmService.java
  src/main/java/com/telepigeon/server/service/hurry/HurryService.java
  src/main/java/com/telepigeon/server/service/question/QuestionService.java
  src/test/java/com/telepigeon/server/fcmTest/FcmServiceTest.java
  src/test/java/com/telepigeon/server/question/QuestionServiceTest.java
Labels: 🍥 refactor 🍥

#55 [feat] #52 CD.yml 생성
  .github/workflows/CD.yml
  Dockerfile
Labels: ✨ feat ✨

#54 [feat] 월간 리포트 기능 구현 완료
  src/main/java/com/telepigeon/server/controller/AnswerController.java
  src/main/java/com/telepigeon/server/domain/Answer.java
  src/main/java/com/telepigeon/server/domain/Question.java
  src/main/java/com/telepigeon/server/dto/answer/RankAnswerDto.java
  src/main/java/com/telepigeon/server/dto/answer/response/MonthlyKeywordsDto.java
  src/main/java/com/telepigeon/server/exception/code/NotFoundErrorCode.java
  src/main/java/com/telepigeon/server/repository/AnswerRepository.java
  src/main/java/com/telepigeon/server/repository/QuestionRepository.java
  src/main/java/com/telepigeon/server/security/filter/FilterUtil.java
  src/main/java/com/telepigeon/server/security/filter/JwtAuthenticationFilter.java
  src/main/java/com/telepigeon/server/security/filter/JwtExceptionFilter.java
  src/main/java/com/telepigeon/server/service/answer/AnswerRetriever.java
  src/main/java/com/telepigeon/server/service/answer/AnswerService.java
  src/main/java/com/telepigeon/server/service/openAi/OpenAiService.java
  src/main/java/com/telepigeon/server/service/question/QuestionRetriever.java
  src/main/java/com/telepigeon/server/service/question/QuestionService.java
  src/main/java/com/telepigeon/server/service/room/RoomService.java
  src/test/java/com/telepigeon/server/answer/AnswerDomainTest.java
  src/test/java/com/telepigeon/server/question/QuestionDomainTest.java
  src/test/java/com/telepigeon/server/question/QuestionServiceTest.java
  src/test/java/com/telepigeon/server/roomTest/RoomServiceTest.java
Labels: ✨ feat ✨

#61 [feat] MethodArgumentNotValid 커스텀에러 추가
  src/main/java/com/telepigeon/server/advice/GlobalExceptionHandler.java
  src/main/java/com/telepigeon/server/exception/code/IllegalArgumentErrorCode.java
Labels: ✨ feat ✨

#63 [fix] firebaseconfig 수정
  src/main/java/com/telepigeon/server/config/FirebaseConfig.java
  src/main/java/com/telepigeon/server/service/fcm/FcmService.java
Labels: 🛠️ fix ⚒️

#59 [fix] Room 입장 분기처리 추가
  .github/workflows/CD.yml
  src/main/java/com/telepigeon/server/exception/code/BusinessErrorCode.java
  src/main/java/com/telepigeon/server/repository/ProfileRepository.java
  src/main/java/com/telepigeon/server/service/profile/ProfileRetriever.java
  src/main/java/com/telepigeon/server/service/profile/ProfileService.java
  src/main/java/com/telepigeon/server/service/room/RoomService.java
Labels: 🛠️ fix ⚒️

#72 [fix] Profile 생성자 수정
  src/main/java/com/telepigeon/server/domain/Profile.java
Labels: 🛠️ fix ⚒️

#85 [feat] S3 적용
  build.gradle
  src/main/java/com/telepigeon/server/config/AwsConfig.java
  src/main/java/com/telepigeon/server/controller/AnswerController.java
  src/main/java/com/telepigeon/server/domain/Answer.java
  src/main/java/com/telepigeon/server/dto/answer/request/AnswerCreateDto.java
  src/main/java/com/telepigeon/server/service/answer/AnswerService.java
  src/main/java/com/telepigeon/server/service/external/NaverCloudService.java
  src/main/java/com/telepigeon/server/service/external/S3Service.java
  src/main/resources/application-test.yml
  src/test/java/com/telepigeon/server/answerTest/AnswerDomainTest.java
  src/test/java/com/telepigeon/server/authTest/AuthServiceTest.java
  src/test/java/com/telepigeon/server/questionTest/QuestionDomainTest.java
  src/test/java/com/telepigeon/server/questionTest/QuestionServiceTest.java
  src/test/resources/application-test.yml
Labels: ✨ feat ✨

#89 [feat] Worry Cron 추가
  src/main/java/com/telepigeon/server/domain/Worry.java
  src/main/java/com/telepigeon/server/repository/WorryRepository.java
  src/main/java/com/telepigeon/server/service/ScheduleService.java
  src/main/java/com/telepigeon/server/service/answer/AnswerService.java
  src/main/java/com/telepigeon/server/service/external/FcmService.java
  src/main/java/com/telepigeon/server/service/hurry/HurryService.java
  src/main/java/com/telepigeon/server/service/profile/ProfileRetriever.java
  src/main/java/com/telepigeon/server/service/question/QuestionService.java
  src/main/java/com/telepigeon/server/service/room/RoomService.java
  src/main/java/com/telepigeon/server/service/worry/WorryRetriever.java
  src/test/java/com/telepigeon/server/questionTest/QuestionServiceTest.java
Labels: ✨ feat ✨

#92 [fix] multipart 수정
  src/main/java/com/telepigeon/server/service/answer/AnswerService.java
Labels: 🛠️ fix ⚒️

#95 [fix] Common 문제 해결
  src/main/java/com/telepigeon/server/controller/ProfileController.java
  src/main/java/com/telepigeon/server/domain/Profile.java
  src/main/java/com/telepigeon/server/dto/type/AgeRange.java
  src/main/java/com/telepigeon/server/dto/type/Gender.java
  src/main/java/com/telepigeon/server/dto/type/Relation.java
  src/main/java/com/telepigeon/server/service/profile/ProfileService.java
  src/main/java/com/telepigeon/server/service/profile/ProfileUpdater.java
  src/test/java/com/telepigeon/server/profileTest/ProfileServiceTest.java
Labels: 🛠️ fix ⚒️

#112 [feat] emotion 특정 점수 및이면 fcm알림 추가
  src/main/java/com/telepigeon/server/dto/type/FcmContent.java
  src/main/java/com/telepigeon/server/service/answer/AnswerService.java
Labels: ✨ feat ✨
