Repository TelePigeon/TelePigeon-Server, pull requests merged in 2024-05, with the labels that each got.

#15 [feat] #14 redis 초기 세팅 완료
  build.gradle
  src/main/java/com/telepigeon/server/config/RedisConfig.java
  src/main/resources/application.yml
Labels: ✨ feat ✨

#23 [fix] 프로젝트 세팅 일부 수정
  .github/workflows/CI.yml
  .gitignore
  src/main/resources/application-example.yml
Labels: 🛠️ fix ⚒️

#26 [refact] 16, 18이슈 옮기기 및 firebase key CI.yml에 등록
  .github/workflows/CI.yml
  .gitignore
  build.gradle
  src/main/java/com/telepigeon/server/advice/GlobalExceptionHandler.java
  src/main/java/com/telepigeon/server/config/FirebaseConfig.java
  src/main/java/com/telepigeon/server/controller/HurryController.java
  src/main/java/com/telepigeon/server/domain/Answer.java
  src/main/java/com/telepigeon/server/domain/Hurry.java
  src/main/java/com/telepigeon/server/domain/Question.java
  src/main/java/com/telepigeon/server/dto/answer/request/AnswerCreateDto.java
  src/main/java/com/telepigeon/server/dto/fcm/FcmMessageDto.java
  src/main/java/com/telepigeon/server/dto/hurry/HurryDto.java
  src/main/java/com/telepigeon/server/exception/code/BusinessErrorCode.java
  src/main/java/com/telepigeon/server/exception/code/NotFoundErrorCode.java
  src/main/java/com/telepigeon/server/repository/AnswerRepository.java
  src/main/java/com/telepigeon/server/repository/HurryRepository.java
  src/main/java/com/telepigeon/server/repository/QuestionRepository.java
  src/main/java/com/telepigeon/server/service/answer/AnswerEditor.java
  src/main/java/com/telepigeon/server/service/answer/AnswerRetriever.java
  src/main/java/com/telepigeon/server/service/answer/AnswerSaver.java
  src/main/java/com/telepigeon/server/service/fcm/FcmService.java
  src/main/java/com/telepigeon/server/service/hurry/HurryRemover.java
  src/main/java/com/telepigeon/server/service/hurry/HurryRetriever.java
  src/main/java/com/telepigeon/server/service/hurry/HurrySaver.java
  src/main/java/com/telepigeon/server/service/hurry/HurryService.java
  src/main/java/com/telepigeon/server/service/question/QuestionRetriever.java
  src/main/java/com/telepigeon/server/service/question/QuestionSaver.java
  src/test/java/com/telepigeon/server/answer/AnswerDomainTest.java
  src/test/java/com/telepigeon/server/fcmTest/FcmServiceTest.java
  src/test/java/com/telepigeon/server/hurryTest/HurryDomainTest.java
  src/test/java/com/telepigeon/server/hurryTest/HurryServiceTest.java
  src/test/java/com/telepigeon/server/question/QuestionDomainTest.java
Labels: ✨ feat ✨, 🍥 refactor 🍥

#29 [add] #27 User 부분 추가
  src/main/java/com/telepigeon/server/controller/RoomController.java
  src/main/java/com/telepigeon/server/exception/code/NotFoundErrorCode.java
  src/main/java/com/telepigeon/server/repository/ProfileRepository.java
  src/main/java/com/telepigeon/server/service/profile/ProfileRetriever.java
  src/main/java/com/telepigeon/server/service/room/RoomService.java
  src/test/java/com/telepigeon/server/roomTest/RoomServiceTest.java
Labels: ➕ add ➕

#32 [feat] #21 Room 관련 API
  src/main/java/com/telepigeon/server/controller/RoomController.java
  src/main/java/com/telepigeon/server/domain/Answer.java
  src/main/java/com/telepigeon/server/domain/Profile.java
  src/main/java/com/telepigeon/server/domain/Users.java
  src/main/java/com/telepigeon/server/dto/room/request/RoomCreateDto.java
  src/main/java/com/telepigeon/server/dto/room/request/RoomEnterDto.java
  src/main/java/com/telepigeon/server/dto/room/response/RoomInfoDto.java
  src/main/java/com/telepigeon/server/dto/room/response/RoomListDto.java
  src/main/java/com/telepigeon/server/exception/code/NotFoundErrorCode.java
  src/main/java/com/telepigeon/server/repository/AnswerRepository.java
  src/main/java/com/telepigeon/server/repository/ProfileRepository.java
  src/main/java/com/telepigeon/server/repository/QuestionRepository.java
  src/main/java/com/telepigeon/server/repository/RoomRepository.java
  src/main/java/com/telepigeon/server/repository/WorryRepository.java
  src/main/java/com/telepigeon/server/service/answer/AnswerRemover.java
  src/main/java/com/telepigeon/server/service/answer/AnswerRetriever.java
  src/main/java/com/telepigeon/server/service/profile/ProfileRemover.java
  src/main/java/com/telepigeon/server/service/profile/ProfileRetriever.java
  src/main/java/com/telepigeon/server/service/question/QuestionRemover.java
  src/main/java/com/telepigeon/server/service/question/QuestionRetriever.java
  src/main/java/com/telepigeon/server/service/room/RoomRetriever.java
  src/main/java/com/telepigeon/server/service/room/RoomService.java
  src/main/java/com/telepigeon/server/service/user/UserRetriever.java
  src/main/java/com/telepigeon/server/service/worry/WorryRemover.java
  src/main/java/com/telepigeon/server/service/worry/WorryRetriever.java
  src/main/java/com/telepigeon/server/service/worry/WorrySaver.java
  src/main/resources/application-test.yml
  src/test/java/com/telepigeon/server/roomTest/RoomServiceTest.java
  src/test/resources/application-test.yml
Labels: ✨ feat ✨

#30 [feat] 질문 생성(ai 제외) 및 최신 질문 조회 완료
  src/main/java/com/telepigeon/server/ServerApplication.java
  src/main/java/com/telepigeon/server/controller/HurryController.java
  src/main/java/com/telepigeon/server/controller/QuestionController.java
  src/main/java/com/telepigeon/server/dto/question/response/GetLastQuestionDto.java
  src/main/java/com/telepigeon/server/exception/code/BusinessErrorCode.java
  src/main/java/com/telepigeon/server/exception/code/NotFoundErrorCode.java
  src/main/java/com/telepigeon/server/service/fcm/FcmService.java
  src/main/java/com/telepigeon/server/service/question/QuestionRetriever.java
  src/main/java/com/telepigeon/server/service/question/QuestionService.java
  src/main/java/com/telepigeon/server/service/room/RoomRetriever.java
  src/test/java/com/telepigeon/server/question/QuestionServiceTest.java
Labels: ✨ feat ✨
